# configs/barlow_twins.yaml
_base_: base.yaml

General:
  model_name: barlow_twins

Training:
  epochs: 300
  batch_size: 256
  optimizer: lars
  learning_rate: 0.2
  weight_decay: 1.5e-6
  warmup_epochs: 10

BarlowTwins:
  projection_dim: 8192
  projection_hidden_dim: 8192
  lambda_coeff: 0.0051             # off-diagonal penalty weight
